---
apiVersion: v1
kind: Namespace
metadata:
    name: cde
    labels:
        env: dev
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api-deployment
  namespace: cde
  labels:
    component: api
spec:
  selector:
    matchLabels:
        component: api
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: api-container
        image: avishnyakov/k8s-api-guid-generator:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: cde
  labels:
    component: api
spec:
  selector:
    component: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: explorer
  namespace: cde
  labels:
    component: explorer
spec:
  containers:
  - name: explorer
    image: dolphm/network-tools
    command: ["/bin/sh", "-c", "sleep 3600;"]